version: 2

jobs:
  build:
    docker:
      - image: betagouv/transport:0.1.0
        environment:
          MIX_ENV: test
          MONGODB_URL: mongodb://localhost/transport_test
          DATATOOLS_URL: http://localhost:4000
          DATAGOUVFR_SITE: https://www.data.gouv.fr
          MAILCHIMP_NEWSLETTER_URL: //gouv.us13.list-manage.com/subscribe/post?u=5ee8bfe0f1b073b49de06a063&amp;id=13db2e9a94
      - image: mongo:3.7-jessie
      - image: wernight/phantomjs
        command: phantomjs --webdriver=8910

    steps:
      - checkout

      - restore_cache:
          keys:
            - elixir-{{ checksum "mix.lock" }}

      - restore_cache:
          keys:
            - node-{{ checksum "client/yarn.lock" }}

      - run:
          name: Install dependencies
          command: |
            mix deps.get
            mix yarn install

      - run:
          name: Run compile
          command: |
            mix deps.compile
            mix compile
            cd client && npm run deploy

      - save_cache:
          key: elixir-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix

      - save_cache:
          key: node-{{ checksum "client/yarn.lock" }}
          paths:
            - client/node_modules

      - run:
          name: Run tests
          command: |
            export SECRET_KEY_BASE=`mix phx.gen.secret`
            mix test
            mix test --only integration
            mix test --only solution
            mix test --only external

      - run:
          name: Run linters
          command: |
            mix credo --strict
            mix npm "run linter:ecma"
            mix npm "run linter:riot"
            mix npm "run linter:sass"

      - run:
          name: Setup Heroku
          command: |
            git remote add heroku https://git.heroku.com/transport-beta.git

            cat > ~/.netrc << EOF
            machine api.heroku.com
              login $HEROKU_LOGIN
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_LOGIN
              password $HEROKU_API_KEY
            EOF

            ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts

      - add_ssh_keys:
          fingerprints:
            - "ec:1c:68:6e:d7:46:29:87:af:67:46:a2:ea:a5:8e:fb"

      - deploy:
          name: Deploy master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push heroku master
              heroku restart
            fi

